### ISSUE TITLE
kenapa ini bang

### ISSUE THREAD

**Issue by resi616** [rickyfazaa/MySPAMBot-OTP#5]
ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)
ERROR: No matching distribution found for urllib

**Comment by fikrisurya** [comment]
Install urllib nya vroh

**Comment by rickyfazaa** [comment]
Halo halo, Kak @resi616 ! sepertinya ku harus sedikit mengkonfigurasi ulang code ku, sepertinya error itu terjadi karena ada redundan "urliib3" dan "urliib" di kode ku.
![image](https://user-images.githubusercontent.com/66496770/230696560-fefbdaa4-018f-4af0-9cb4-f54de4dc48c1.png)
Akan segera diperbaiki, Terimakasih atas issuenya!

**Comment by resi616** [comment]
ok bang
